---
id: Stream_Wrapper
name: Stream_Wrapper
full: PHP stream wrappers library
description: A library of stream wrappers.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Stream_Wrapper
authors:
  - name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  - name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0
  api: 3.0.0alpha1
state:
  release: stable
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^8
  dev:
    composer:
      horde/log: ^3
  optional:
    composer:
      horde/log: ^3
keywords:
  - decorator
vendor: horde
quality:
  phpstan:
    level: 3
ci-platform:
  '8.0':
    - php: ^8.1
    - ext-dom
  '8.1':
    - php: ^8.1
    - ext-dom
  '8.2':
    - php: ^8.1
    - ext-dom
  '8.3':
    - php: ^8.1
    - ext-dom
  '8.4':
    - php: ^8.1
    - ext-dom
  '8.5':
    - php: ^8.1
    - ext-dom
  '8.6':
    - php: ^8.1
    - ext-dom
ci-platform-flags:
  needs_installer_plugin: false
